### Introduccion a Numpy

Numpy es una biblioteca que permite el manejo y la  manipulación de arreglos y matrices.

In [1]:
#Importar numpy 
import numpy as np

In [2]:
#Creacion de un arreglo
new_array = np.array([[2,3,5,6],[2,5,7,3]])
print(new_array)

[[2 3 5 6]
 [2 5 7 3]]


In [3]:
#Conocer algunas características del arreglo
print("Dimension del arreglo:", new_array.ndim)
print("Tipos de datos que conforman al arreglo:", new_array.dtype)
print("La forma del arreglo:", new_array.shape)

Dimension del arreglo: 2
Tipos de datos que conforman al arreglo: int32
La forma del arreglo: (2, 4)


In [4]:
#Ingresar a algun elemento particular del arreglo con la notacion [renglon, columna]
print(new_array[1,2])
#Acceder a la columna 3 de todos los renglones
print(new_array[:,3])
#Acceder a todas las columnas del renglon 0
print(new_array[0,:])

7
[6 3]
[2 3 5 6]


In [5]:
#Modificar algún elemento del arreglo
new_array[0,0] = 15
new_array

array([[15,  3,  5,  6],
       [ 2,  5,  7,  3]])

In [6]:
#Modificar la forma del arreglo
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
b = np.reshape(a,(4,3))
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
#Repetir elementos para formar un arreglo
arre1 = [1,2,3]
np.repeat([arre1],3, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [8]:
#Inicializar distintos tipos de arreglos

#Arreglo de forma (2,3) con valores 0
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
#Arreglo de forma (4,2) con valores 1
print(np.ones((4,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [10]:
#Arreglo de la forma (2,2) con valor 20
print(np.full((2,2),20))

[[20 20]
 [20 20]]


In [11]:
#Arreglo de la forma (2,3,2) con numeros aleatorios con valor minimo 3 y valor mázimo 15
print(np.random.randint(3,15,size=(2,3,2)))

[[[ 3  8]
  [ 4  9]
  [ 5  9]]

 [[13  6]
  [11 13]
  [ 7  3]]]


In [12]:
#Matriz identidad
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Algebra lineal

In [13]:
a = np.array([1,2,6,7])
print(a+3)
print(a-2)
print(a*4)
print(a/2)
print(np.sin(a))

[ 4  5  9 10]
[-1  0  4  5]
[ 4  8 24 28]
[0.5 1.  3.  3.5]
[ 0.84147098  0.90929743 -0.2794155   0.6569866 ]


In [14]:
#Suma de vectores
a = np.array([6, -2])
b = np.array([-4, 4])
print(a + b)

[2 2]


In [15]:
#Resta de vectores
print(a-b)

[10 -6]


In [16]:
#Multiplicación de matrices
a = np.array([[1,2],[5,8]])
b = np.array([[1,3,5,7],[4,6,8,2]])
np.matmul(a,b)

array([[ 9, 15, 21, 11],
       [37, 63, 89, 51]])

In [17]:
#Obtener el determinante de una matriz
np.linalg.det(a)

-1.9999999999999993

In [18]:
#Obtener la norma de una matriz
np.linalg.norm(a)

9.695359714832659

In [19]:
#Obtener la transpuesta
a.T

array([[1, 5],
       [2, 8]])

In [20]:
#Obtener el producto punto
np.dot(a,b)

array([[ 9, 15, 21, 11],
       [37, 63, 89, 51]])

In [21]:
#Producto cruz o producto vectorial
a = np.array([1,0,0]) 
b = np.array([0,1,0]) 
print(np.cross(a,b))

[0 0 1]
